#!/usr/bin/env python3
"""Generate a coverage audit report across services in the monorepo."""

import os
from datetime import datetime, timezone
from pathlib import Path

SERVICES = [
    "auth-service",
    "transaction-service",
    "pii-service",
    "audit-service",
]

SOURCE_EXTENSIONS = (".java", ".py", ".ts")

AUDIT_REPORTS_DIR = Path("audit_reports")


def is_source_file(path: Path) -> bool:
    name = path.name
    if name.endswith(".d.ts"):
        return False
    return name.endswith(SOURCE_EXTENSIONS)


def is_test_file(rel_path: Path) -> bool:
    if any(part in ("test", "tests") for part in rel_path.parts):
        return True
    name = rel_path.name
    if name.endswith("Test.java"):
        return True
    if name.startswith("test_") and name.endswith(".py"):
        return True
    if name.endswith(".test.ts"):
        return True
    return False


def count_files(service_dir: Path):
    sources = 0
    tests = 0
    for root, _dirs, files in os.walk(service_dir):
        for fname in files:
            full = Path(root) / fname
            rel = full.relative_to(service_dir)
            if not is_source_file(full):
                continue
            if is_test_file(rel):
                tests += 1
            else:
                sources += 1
    return sources, tests


def coverage_estimate(sources: int, tests: int) -> float:
    if sources == 0:
        return 0.0
    return min(tests / sources, 1.0)


def format_pct(cov: float) -> str:
    pct = int(round(cov * 100))
    if pct == 0:
        return "0%"
    return f"~{pct}%"


def build_table(rows, overall_label: str) -> str:
    overall_cell = f"**{overall_label}**" if overall_label != "0%" else "**0%**"
    lines = [
        f"| {'Service':<20} | {'Coverage Estimate':<17} |",
        f"|{'-' * 22}|{'-' * 19}|",
    ]
    for name, _s, _t, cov in rows:
        lines.append(f"| {name:<20} | {format_pct(cov):<17} |")
    lines.append(f"| {'**Overall**':<20} | {overall_cell:<17} |")
    return "\n".join(lines)


def build_audit_report(table: str, overall_label: str, rows) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    zero_coverage = [name for name, _s, _t, cov in rows if cov == 0.0]
    has_coverage = [
        (name, format_pct(cov)) for name, _s, _t, cov in rows if cov > 0.0
    ]

    assessment_lines = []
    for name, pct in has_coverage:
        assessment_lines.append(f"- **{name}** has {pct} estimated coverage.")
    if zero_coverage:
        names = ", ".join(f"**{n}**" for n in zero_coverage)
        assessment_lines.append(f"- {names} — zero test coverage.")

    assessment = "\n".join(assessment_lines) if assessment_lines else "- No data."

    return f"""# Coverage Audit Report

**Report ID:** AUDIT-{now}  
**Generated:** {now}  
**Type:** Coverage Assessment  
**Scope:** All ClearBank Core services  

---

## Summary

Overall estimated test coverage: **{overall_label}**.

## Coverage by Service

{table}

## Assessment

{assessment}

---

*This is an automated audit report generated by ClearBank's coverage tooling.*
"""


def main() -> None:
    rows = []
    total_src = 0
    total_test = 0
    for name in SERVICES:
        service_dir = Path(name)
        if not service_dir.exists():
            continue
        s, t = count_files(service_dir)
        total_src += s
        total_test += t
        rows.append((name, s, t, coverage_estimate(s, t)))

    overall = coverage_estimate(total_src, total_test)
    overall_label = format_pct(overall)

    table = build_table(rows, overall_label)

    # Print the simple table to stdout (used by CI for PR comments)
    print(table)

    # Write full audit report to audit_reports/
    AUDIT_REPORTS_DIR.mkdir(exist_ok=True)
    audit_report = build_audit_report(table, overall_label, rows)
    (AUDIT_REPORTS_DIR / "coverage.md").write_text(audit_report)


if __name__ == "__main__":
    main()
